In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import cluster, metrics
from sklearn.utils import shuffle
import matplotlib.pyplot as plt

In [2]:
def reorder(x):
    col = x.columns.tolist()
    col = col[1:] + [col[0]]
    reorder_data = x[col]
    return reorder_data

In [3]:
path = "../bankruptcy_HW1_train.csv"
data = pd.read_csv(path).drop(["Unnamed: 0"],axis=1)
data = reorder(data)
data

Net worth/Assets   Debt ratio %  \
0              0.888200       0.111800   
1              0.847689       0.152311   
2              0.966895       0.033105   
3              0.906310       0.093690   
4              0.882396       0.117604   
...                 ...            ...   
9257           0.824272       0.175728   
9258           0.786659       0.213341   
9259           0.806011       0.193989   
9260           0.872011       0.127989   
9261           0.837775       0.162225   

       Per Share Net profit before tax (Yuan ¥)  \
0                                      0.184454   
1                                      0.166755   
2                                      0.181969   
3                                      0.167960   
4                                      0.179935   
...                                         ...   
9257                                   0.161288   
9258                                   0.174660   
9259                                   0.193313   
9260                                   0.155082   
9261                                   0.166181   

       ROA(C) before interest and depreciation before interest  Bankrupt?  
0                                              0.500951                 0  
1                                              0.479647                 0  
2                                              0.516502                 0  
3                                              0.446302                 0  
4                                              0.575245                 0  
...                                                 ...               ...  
9257                                           0.467220                 1  
9258                                           0.494583                 1  
9259                                           0.494676                 1  
9260                                           0.417124                 1  
9261                                           0.463788                 1  

[9262 rows x 5 columns]

In [4]:
from sklearn.linear_model import SGDClassifier

In [5]:
clf = SGDClassifier(loss="hinge", penalty="l2", max_iter=1000)
train = np.array(data)
train = shuffle(train)
X, y = train[:, 0:4], train[:, 4]
clf.fit(X, y)

SGDClassifier()

In [6]:
y_train_pred=clf.predict(X)
y_train_pred

array([1., 0., 0., ..., 1., 0., 1.])

In [7]:
test_data = pd.read_csv("../bankruptcy_HW1_test.csv").drop(["Unnamed: 0"],axis=1)
test = reorder(test_data)
test = np.array(shuffle(test))
X_test, y_test = test[:, 0:4], test[:, 4]
clf.fit(X_test, y_test)

SGDClassifier()

In [8]:
y_test_pred=clf.predict(X_test)
y_test_pred

array([0., 0., 0., ..., 0., 0., 0.])

In [9]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
print("Accuracy_train:",accuracy_score(y, y_train_pred))
print(classification_report(y, y_train_pred))
print("Accuracy_test:",accuracy_score(y_test, y_test_pred))
print(classification_report(y_test, y_test_pred))

Accuracy_train: 0.8704383502483265
              precision    recall  f1-score   support

         0.0       0.92      0.82      0.86      4631
         1.0       0.83      0.92      0.88      4631

    accuracy                           0.87      9262
   macro avg       0.87      0.87      0.87      9262
weighted avg       0.87      0.87      0.87      9262

Accuracy_test: 0.9643206256109482
              precision    recall  f1-score   support

         0.0       0.97      1.00      0.98      1968
         1.0       0.73      0.10      0.18        78

    accuracy                           0.96      2046
   macro avg       0.85      0.55      0.58      2046
weighted avg       0.96      0.96      0.95      2046



In [10]:
from sklearn.ensemble import AdaBoostClassifier

In [11]:
clf = AdaBoostClassifier(n_estimators=100, random_state=0)
train = np.array(data)
train = shuffle(train)
X, y = train[:, 0:4], train[:, 4]
clf.fit(X, y)

AdaBoostClassifier(n_estimators=100, random_state=0)

In [12]:
y_train_pred=clf.predict(X)
y_train_pred

array([0., 1., 0., ..., 1., 0., 0.])

In [13]:
test_data = pd.read_csv("../bankruptcy_HW1_test.csv").drop(["Unnamed: 0"],axis=1)
test = reorder(test_data)
test = np.array(shuffle(test))
X_test, y_test = test[:, 0:4], test[:, 4]
clf.fit(X_test, y_test)

AdaBoostClassifier(n_estimators=100, random_state=0)

In [14]:
y_test_pred=clf.predict(X_test)
y_test_pred

array([0., 0., 0., ..., 0., 0., 0.])

In [15]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
print("Accuracy_train:",accuracy_score(y, y_train_pred))
print(classification_report(y, y_train_pred))
print("Accuracy_test:",accuracy_score(y_test, y_test_pred))
print(classification_report(y_test, y_test_pred))

Accuracy_train: 0.8843662275966314
              precision    recall  f1-score   support

         0.0       0.91      0.85      0.88      4631
         1.0       0.86      0.92      0.89      4631

    accuracy                           0.88      9262
   macro avg       0.89      0.88      0.88      9262
weighted avg       0.89      0.88      0.88      9262

Accuracy_test: 0.9745845552297165
              precision    recall  f1-score   support

         0.0       0.98      1.00      0.99      1968
         1.0       0.91      0.37      0.53        78

    accuracy                           0.97      2046
   macro avg       0.94      0.69      0.76      2046
weighted avg       0.97      0.97      0.97      2046

